### ISSUE TITLE
/virtual/main.c:67:16: error: no member named 'type' in 'struct iov_iter'

### ISSUE THREAD

**Issue by vanhauser-thc** [mechpen/sockdump#9]
I tried this with bcc from debian testing as well as removing it and then compiling and installing bcc from the most current repo state:
```
# ./sockdump.py --format string /var/run/docker.sock
/virtual/main.c:67:16: error: no member named 'type' in 'struct iov_iter'
    if ((iter->type & WRITE) == 0 || iter->iov_offset != 0) {
         ~~~~  ^
1 error generated.
Traceback (most recent call last):
  File "/prg/tmp/sockdump/./sockdump.py", line 335, in <module>
    main(args)
  File "/prg/tmp/sockdump/./sockdump.py", line 281, in main
    b = BPF(text=text)
  File "/usr/lib/python3/dist-packages/bcc/__init__.py", line 479, in __init__
    raise Exception("Failed to compile BPF module %s" % (src_file or "<text>"))
Exception: Failed to compile BPF module <text>
```
kernel is 5.14.0

**Comment by vnznznz** [comment]
Edit: this wrong, see later comment
> I fixed it by changing `sockdump.py` line 79 from `if ((iter->type & WRITE) == 0` to `if ((iter->iter_type & WRITE) == 0`

**Comment by vnznznz** [comment]
But this cause sockdump to only print `error` for message contents, currently trying to understand this change to fix this https://github.com/torvalds/linux/commit/8cd54c1c848031a87820e58d772166ffdf8c08c0

**Comment by vnznznz** [comment]
ah damn you need to change the line to `if ((!iter->data_source)`

**Comment by vanhauser-thc** [comment]
both make it so it does not complain, but both also result in no data being seen.

```
# ./sockdump.py --format string /tmp/SockSniffer/server.sock
waiting for data
```
while sending messages back and forth on server.sock
(needs server.sock in client.pl to work: https://9821e5c2-a-62cb3a1a-s-sites.googlegroups.com/site/wiedzminconrad/SockSniffer.v0.1.tar.gz?attachauth=ANoY7cqMPjg3E4HKTsrUcbrcWX6AUpshuCQMSI8AXDCnCke3Zazp0_Xz1Bn0EdS17B_Dn0HuYKPNtT4RmAmFcU4qOIY1t4CjfbqaoNVO7wffT2-9XEfO2Vwxxr7pjwiL8AFwv0Z1Daaf3twQWDUpN6WGIHgDRar1RIY_uAR-PECj-IcWwziZC8BSRl4Krz1IqZu5RPLiIpuh8IwCKbnk72BiZyDBGzqsEnLrBRIfQwQaWkPUHaOwixY%3D&attredirects=0)

**Comment by vnznznz** [comment]
did you leave the rest of line 79? it works for me with `if ((!iter->data_source) || iter->iov_offset != 0) {`

**Comment by vanhauser-thc** [comment]
yes, this is how it looks like:

```
$ git diff
diff --git a/sockdump.py b/sockdump.py
index 4ca01ba..d45ade5 100755
--- a/sockdump.py
+++ b/sockdump.py
@@ -76,7 +76,7 @@ int probe_unix_socket_sendmsg(struct pt_regs *ctx,
     packet->peer_pid = sock->sk->sk_peer_pid->numbers[0].nr;
 
     iter = &msg->msg_iter;
-    if ((iter->type & WRITE) == 0 || iter->iov_offset != 0) {
+    if ((!iter->data_source) == 0 || iter->iov_offset != 0) {
         packet->len = len;
         packet->flags = SS_PACKET_F_ERR;
         events.perf_submit(ctx, packet, offsetof(struct packet, data));
```

**Comment by mechpen** [comment]
Thanks for reporting the issue.  This should be fixed now.

**Comment by vanhauser-thc** [comment]
still doesnt work for me, no socket read/write are seen:

```
./sockdump.py --format string /tmp/SockSniffer/server.sock
waiting for data
```
while with strace is see it:
```
# strace -e trace=read,write -e read=3 -e write=3 -p 955229
strace: Process 955229 attached
read(4, "Data 1\n", 8192)               = 7
write(4, "odpowied\305\272\n", 11)      = 11
read(4, "Data 2\n", 8192)               = 7
write(4, "odpowied\305\2722\n", 12)     = 12
read(4, "", 8192)                       = 0
```
kernel 5.14.0 

srwxr-xr-x 1 root root 0 Dec 21 11:10 server.sock

**Comment by mechpen** [comment]
Is your process using relative path or symlink to `/tmp/SockSniffer/server.sock` as the sockaddr?  The path to `sockdump.py` must be the same path string in the process.

For example, `/var/run/docker.sock` and `/run/docker.sock` are the same file.  Because docker uses `/run/docker.sock` in the socked address, running `sockdump.py `/var/run/docker.dock` will not not work.

**Comment by vanhauser-thc** [comment]
ah that is the issue.
the scripts used "server.sock", I started sockdump from a different directory and used the full path.
isnt it possible to some matching on the name? Otherwise it would first need to find out the exact name being used which could be something like "../../foo/bar/sock"
